//Import features from Material UI libraries
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import CancelIcon from "@mui/icons-material/Cancel";
import CancelPresentationIcon from "@mui/icons-material/CancelPresentation";
import Checkbox from "@mui/material/Checkbox";
import CheckBoxIcon from "@mui/icons-material/CheckBox";
import DeleteIcon from "@mui/icons-material/Delete";
import EditIcon from "@mui/icons-material/Edit";
import Grid from "@mui/material/Grid";
import IconButton from "@mui/material/IconButton";
import HomeIcon from "@mui/icons-material/Home";
import Item from "@mui/material/Stack";
import ListIcon from "@mui/icons-material/List";
import LogoutIcon from "@mui/icons-material/Logout";
import MuiAlert from "@mui/material/Alert";
import Paper from "@mui/material/Paper";
import PersonSearchIcon from "@mui/icons-material/PersonSearch";
import PreviewOutlinedIcon from "@mui/icons-material/PreviewOutlined";
import RefreshOutlinedIcon from "@mui/icons-material/RefreshOutlined";
import SaveIcon from "@mui/icons-material/Save";
import SearchOutlinedIcon from "@mui/icons-material/SearchOutlined";
import Snackbar from "@mui/material/Snackbar";
import Stack from "@mui/material/Stack";
import SystemUpdateAltIcon from "@mui/icons-material/SystemUpdateAlt";
import Tab from "@mui/material/Tab";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Tabs from "@mui/material/Tabs";
import TextField from "@mui/material/TextField";

//Make the features available for import
export const BoxUI = Box;
export const ButtonUI = Button;
export const GridUI = Grid;
export const CancelIconUI = CancelIcon;
export const CancelPresentationIconUI = CancelPresentationIcon;
export const CheckBoxIconUI = CheckBoxIcon;
export const CheckboxUI = Checkbox;
export const DeleteIconUI = DeleteIcon;
export const EditIconUI = EditIcon;
export const HomeIconUI = HomeIcon;
export const IconButtonUI = IconButton;
export const ItemUI = Item;
export const ListIconUI = ListIcon;
export const LogoutIconUI = LogoutIcon;
export const MuiAlertUI = MuiAlert;
export const PaperUI = Paper;
export const PersonSearchIconUI = PersonSearchIcon;
export const PreviewOutlinedIconUI = PreviewOutlinedIcon;
export const RefreshOutlinedIconUI = RefreshOutlinedIcon;
export const SaveIconUI = SaveIcon;
export const SearchOutlinedIconUI = SearchOutlinedIcon;
export const SnackbarUI = Snackbar;
export const StackUI = Stack;
export const SystemUpdateAltIconUI = SystemUpdateAltIcon;
export const TableBodyUI = TableBody;
export const TableCellUI = TableCell;
export const TableContainerUI = TableContainer;
export const TextFieldUI = TextField;
export const TableHeadUI = TableHead;
export const TableRowUI = TableRow;
export const TableUI = Table;
export const TabsUI = Tabs;
export const TabUI = Tab;
